MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
RGBLIGHT_ENABLE = yes
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
WPM_ENABLE = yes


TAP_DANCE_ENABLE = no
BOOTMAGIC_ENABLE = no
CAPS_WORD_ENABLE = no
COMBO_ENABLE = no
SWAP_HANDS_ENABLE = no


CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
MUSIC_ENABLE = no 
MIDI_ENABLE = no 
BLUETOOTH_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
AUTO_SHIFT_ENABLE = no
